# Generated by Django 4.2.2 on 2023-07-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_session_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
    ]
